---
#----------------------------------------------------------------------------
# .terraform-docs.yml
# use the following command to install on a Mac:
# brew install terraform-docs
#----------------------------------------------------------------------------

settings:
anchor: false

sort:
  enabled: true
  by: required
